### ISSUE TITLE
mark task as done

### ISSUE THREAD

**Issue by kextique** [cs2103jan2016-W10-1J/main#86]
move done items to archive

**Comment by natthaniel** [comment]
```
1. [ ]Mark Done
    1. [ ]add in a field in Task.java to mark done/undone, set default as undone.
    2. [ ]add in public setter function Task to mark done
    3. [ ]Setting up a separate array-list for done tasks in the storage, providing relevant getter function for accessibility
```
